pathways:
  default: workshop

  paths:
    workshop:
      title: "Workshop"

      steps:
      - 00-workshop-prerequisites
      - 00-workshop-overview
      - 01-important-ai-concepts
      - 02-running-the-lab
      - 03-first-spring-ai-app
      - 04-prompts
      - 05-roles
      - 06-embedding
      - 07-retrieval-augmented-generation
